"""Second Migration

Revision ID: 45c414209559
Revises: a01bbbc1e108
Create Date: 2022-09-08 19:59:29.948314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c414209559'
down_revision = 'a01bbbc1e108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Contacts', 'createdBy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Contacts', sa.Column('createdBy', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
