"""Initial Cloud Migration

Revision ID: 7cf314440c2f
Revises: 
Create Date: 2022-10-03 09:46:42.274857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf314440c2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contacts',
    sa.Column('contactID', sa.Integer(), nullable=False),
    sa.Column('fName', sa.String(length=50), nullable=False),
    sa.Column('lName', sa.String(length=50), nullable=True),
    sa.Column('mName', sa.String(length=50), nullable=True),
    sa.Column('workCompany', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('homePhone', sa.String(length=20), nullable=True),
    sa.Column('workPhone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('jobTitle', sa.String(length=50), nullable=True),
    sa.Column('imageURL', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('contactID')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passcode', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_Admin', sa.Boolean(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passcode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Contacts')
    # ### end Alembic commands ###
