"""Initial Migration

Revision ID: a01bbbc1e108
Revises: 
Create Date: 2022-09-08 19:50:52.847689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01bbbc1e108'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contacts',
    sa.Column('contactID', sa.Integer(), nullable=False),
    sa.Column('fName', sa.String(), nullable=False),
    sa.Column('lName', sa.String(), nullable=False),
    sa.Column('mName', sa.String(), nullable=False),
    sa.Column('workCompany', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=False),
    sa.Column('homePhone', sa.String(), nullable=True),
    sa.Column('workPhone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('jobTitle', sa.String(), nullable=True),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('contactID')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passcode', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_Admin', sa.Boolean(), nullable=False),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('passcode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Contacts')
    # ### end Alembic commands ###
