"""empty message

Revision ID: cb2ce5c0409b
Revises: 45c414209559
Create Date: 2022-09-13 11:54:11.883736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2ce5c0409b'
down_revision = '45c414209559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Contacts', sa.Column('imageURL', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Contacts', 'imageURL')
    # ### end Alembic commands ###
